### ISSUE TITLE
Why not LeviLamina or Endstone

### ISSUE THREAD

**Issue by killcerr** [Elec-Glacier/liteloader_handler#10]
支持LeviLamina 或者 Endstone。
liteloaderbds已经过老了，对于大多数服务器来说。

**Comment by Elec-Glacier** [comment]
之后会支持，与原版的script api输出玩家聊天的一起。

**Comment by jiangyan03** [comment]
> 支持LeviLamina 或者 Endstone。
> liteloaderbds已经过老了，对于大多数服务器来说。

内部有LeviLamina和Endstone支持，稍后版本发布

**Comment by Elec-Glacier** [comment]
已添加对Levilamina的支持。endstone的输出是跟原版一样，无需做特殊的处理
