### ISSUE TITLE
处理器使用限制

### ISSUE THREAD

**Issue by Mooling0602** [Elec-Glacier/liteloader_handler#9]
鉴于基岩版不支持/data命令，以此为基础的[Minecraft Data API](https://mcdreforged.com/zh-CN/plugin/minecraft_data_api)及使用该API的各种MCDR插件均无法使用。
针对Java版特有日志开发的插件，也有这种情况（例如IPLocation等）
个人建议：
- 推荐：在README等处增加相关提示，使非专业用户使用处理器前了解到相关信息
- 开发第三方ll插件使服务端支持/data命令、增加Java版特有的日志输出等

**Comment by Elec-Glacier** [comment]
感谢建议，已修改README增加提示。
有第三方ll插件支持/data命令，但使用方法和输出结构都十分不同，故还是得用户使用插件前自行注意兼容性
